# Generated by Django 3.2.12 on 2023-05-25 02:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='', max_length=30, unique=True)),
                ('realname', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=40)),
                ('region', models.CharField(choices=[('서울', 'Seoul'), ('경기', 'Gyeonggi'), ('인천', 'Incheon'), ('부산', 'Busan')], default='', max_length=40)),
                ('sex', models.CharField(blank=True, choices=[('남성', 'Male'), ('여성', 'Female')], max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('ready_money', models.IntegerField(blank=True, null=True)),
                ('profile_public', models.BooleanField(default=True)),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('follower', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('stock_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_access_count', models.IntegerField(default=0)),
                ('bond_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bond_access_count', models.IntegerField(default=0)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_access_count', models.IntegerField(default=0)),
                ('cash_equivalents_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_equivalents_access_count', models.IntegerField(default=0)),
                ('property_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_hyup_count', models.IntegerField(default=0)),
                ('cash_content_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
